name: Tracker Max Jeune

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Installer les dépendances
        run: pip install requests
        
      - name: Exécuter le script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check_trains.py
